### ISSUE TITLE
ERROR Manifest merger failed when just trying step 4

### ISSUE THREAD

**Issue by thestigmister** [firebase/friendlychat-android#88] opened 2020-02-16 15:33 UTC
I'm trying to just get started with the Codelab. I did all the stuff in the Firebase console to add the app to it. And then when I did Gradle sync, I keep getting this error:
```
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-22:19 to override.
```
Is the solution to do Refactor> Migrate to AndroidX?
It does seem to work, but if it's not the right thing to do, can someone please get this sorted?

Seems ridiculous that the tutorial isn't even up to date. This is putting me off using Firebase if I can't even get a tutorial working. 

Also, after having done this and trying to run the app on my phone, it keeps stopping saying "Friendly chat has stopped" and keeps stopping. Can't even get Firebase to verify installation by running the app cos it doesn't work.

**Comment by samtstern** [comment] 2020-02-19 00:47
@thestigmister did you maybe update some dependencies?  This could be the cause of the issue.

**Comment by samtstern** [comment] 2020-02-25 21:34
I did a lot of updates today, this should be fixed.  Try getting the latest code and thanks for reporting!

**Closed by samtstern** 2020-02-25 21:34 UTC
